// utils/mockData.ts
import { AFPCase, FacilityVisit } from "../types";

export const mockCases: AFPCase[] = [
  // August / September style seed (two-month spread)
  {
    id: "case-202508-001",
    patientName: "Amina Bello",
    age: 3,
    gender: "Female",
    address: "45 Ogun Street",
    caseSource: "Ward",
    wardDetected: "Pediatric Ward",
    specimenCollected: true,
    specimenDate: "2025-08-12",
    remarks: "AFP-like symptoms",
    facilityName: "Katsina General Hospital",
    state: "Katsina",
    lga: "Katsina",
    weekNumber: 36,
    createdAt: "2025-08-12T10:00:00Z",
    updatedAt: "2025-08-12T10:00:00Z",
    finalized: true,
  },
  {
    id: "case-202509-002",
    patientName: "Sani Lawal",
    age: 4,
    gender: "Male",
    address: "12 Zaria Road",
    caseSource: "Incoming Patient",
    wardDetected: null,
    specimenCollected: false,
    specimenDate: null,
    remarks: "Referred case",
    facilityName: "Katsina General Hospital",
    state: "Katsina",
    lga: "Katsina",
    weekNumber: 39,
    createdAt: "2025-09-02T09:30:00Z",
    updatedAt: "2025-09-02T09:30:00Z",
    finalized: true,
  },
  // add a few more for immediate testing
  {
    id: "case-202510-001",
    patientName: "Hassan Musa",
    age: 5,
    gender: "Male",
    address: "Sabon Gari",
    caseSource: "Ward",
    wardDetected: "Emergency Ward",
    specimenCollected: true,
    specimenDate: "2025-10-12",
    remarks: "",
    facilityName: "Katsina General Hospital",
    state: "Katsina",
    lga: "Katsina",
    weekNumber: 42,
    createdAt: "2025-10-12T08:30:00Z",
    updatedAt: "2025-10-12T08:30:00Z",
    finalized: false,
  },
];

export const mockVisits: FacilityVisit[] = [
  {
    id: "visit-202508-001",
    facilityName: "Katsina General Hospital",
    state: "Katsina",
    lga: "Katsina",
    month: "August",
    weekNumber: 36,
    unitsVisited: ["Pediatric Ward", "OPD"],
    visitDate: "2025-08-12",
    healthWorkerSignature: "Dr. Abubakar",
    casesFound: 1,
    createdAt: "2025-08-12T16:00:00Z",
    finalized: true,
  },
  {
    id: "visit-202509-001",
    facilityName: "Katsina General Hospital",
    state: "Katsina",
    lga: "Katsina",
    month: "September",
    weekNumber: 39,
    unitsVisited: ["Emergency Ward", "ICU"],
    visitDate: "2025-09-02",
    healthWorkerSignature: "Dr. Amina",
    casesFound: 1,
    createdAt: "2025-09-02T17:30:00Z",
    finalized: true,
  },
];
